### PR TITLE
Fix: [EL-4704] create toolkit form UI issues

### LINKED ISSUE #4704: [BUG] Replace incorrect input fields in Create Toolkit form with proper component from Storybook.
**Description:** 
Some input fields in the Create Toolkit forms have incorrect styling, causing inconsistencies in the platform UI.

**Fix:** 
**1. Check all Create [toolkit type] forms and fix the input field "Description" and fields that have incorrect default state (with the label on the top and empty space for input data).** 
"Description" field should be the same as "Description" in Create Agent page.
Default Input state must comply with the established component style in Storybook.

Here is screenshot with incorrect input fields example - 

Image

> 

**2. Set equal paddings between fields at least 8px.** 
Expected:

Image
Image

> 

**3. Expand scroll area.** 
For now scroll works when cursor is in form frame.

Image

> 

**4. Replace tab-switcher (Form-RawJson) with pproper component from Storybook**

Image

### PR DESCRIPTION
**Pull request by OlgaPrikhodko**
The changes cover four main areas:

- toolkit form spacing and scroll behavior
- loading state alignment on the create toolkit form
- label and tooltip consistency for credential and model selectors
- refactoring `FormViewToggle` to use the shared tab button pattern

### 1. Fixed toolkit form layout and scrolling

- added consistent vertical spacing between toolkit configuration fields
- moved scrolling responsibility to the parent container to avoid nested scroll issues
- removed conflicting internal overflow constraints from `ToolkitForm`
- updated chat toolkit editor and toolkit configuration containers to render the form without clipping

### 2. Aligned loading state behavior

- centered the `ToolkitForm` loading spinner so it matches the loader pattern used on the agent view page
- prevented the loading indicator from rendering in the top-left corner during create flow data loading

### 3. Standardized label and tooltip rendering

- replaced custom label + tooltip markup in `CredentialsSelect` with shared `InfoLabelWithTooltip`
- replaced custom label + tooltip markup in `EmbeddingModelSelect` with shared `InfoLabelWithTooltip`
- updated toolkit base property inputs to pass tooltip descriptions through the shared input path instead of
  custom label rendering
- enhanced `InfoLabelWithTooltip` to support:
  - required marker rendering
  - custom label styles
  - configurable tooltip icon sizing
- aligned text field label/icon scaling with the Simple input variant and design spec

### 4. Refactored form/raw-json toggle

- replaced custom MUI `ToggleButtonGroup` implementation in `FormViewToggle` with shared `TabGroupButton`
- preserved the existing public API while simplifying the component structure
- brought the component in line with project memoization and handler patterns

image

image

### CODE REVIEW

**Review by mShamanskyi — APPROVED** [review]

File: src/components/CredentialsSelect.jsx [hunk 1]
```diff
@@ -449,26 +448,25 @@ const CredentialsSelect = memo(
     const customRenderSelectValue = useCallback(
       foundOption => {
         if (!foundOption) {
+          if (!value?.elitea_title) return null;
```
Comment (HawkQing1) [inline src/components/CredentialsSelect.jsx:451]: We should render "Select credentials" for empty value here. Like this
`              <Typography
                variant="labelMedium"
                sx={styles.unmatchedValueTypography(hasFetchedData)}
              >
                Select credentials
              </Typography>
`

**Review by HawkQing1 — COMMENTED** [review]
@OlgaPrikhodko please take a look at my comment

File: src/components/CredentialsSelect.jsx (hunk 1 above)
Comment (OlgaPrikhodko) [reply src/components/CredentialsSelect.jsx:451]: by design we don't need placeholder 

image
